using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Milionaire
{
    public class Question
    {
        public int Difficulty { get; set; }
        public string QuestionName { get; set; }
        public string WrongAnswer1 { get; set; }
        public string WrongAnswer2 { get; set; }
        public string WrongAnswer3 { get; set; }
        public string RightAnswer { get; set; }

        public static void PopulateQuestionList(List<Question> _QuestionList)
        {
            _QuestionList.Add(new Question { QuestionName = "Что, согласно известному фразеологизму, дают, затевая драку?", RightAnswer = "Волю рукам", WrongAnswer1 = "Голову на отсечение", WrongAnswer2 = "Деру", WrongAnswer3 = "Дуба", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "На что надевается автомобильная шина?", RightAnswer = "На диски", WrongAnswer1 = "На пластинки", WrongAnswer2 = "На кассеты", WrongAnswer3 = "На барабаны", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Что первым сделал Алексей Леонов в марте 1965 года, войдя тем самым в историю?", RightAnswer = "Вышел в открытый космос", WrongAnswer1 = "Вышел покурить", WrongAnswer2 = "Вышел за хлебом", WrongAnswer3 = "Открыл 109 химический элемент", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Как называется гибкий пожарный трубопровод для тушения огня?", RightAnswer = "Рукав", WrongAnswer1 = "Манжета", WrongAnswer2 = "Карман", WrongAnswer3 = "Вытачка", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Как иначе называют инжир?", RightAnswer = "Фига", WrongAnswer1 = "Кукиш", WrongAnswer2 = "Дуля", WrongAnswer3 = "Шиш", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Какой город есть на Украине?", RightAnswer = "Кривой Рог", WrongAnswer1 = "Прямой хвост", WrongAnswer2 = "Большое Копыто", WrongAnswer3 = "Густая грива", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Какой вид тепловой обработки производится в фритюрнице?", RightAnswer = "Обжаривание", WrongAnswer1 = "Пропаривание", WrongAnswer2 = "Варка", WrongAnswer3 = "Замораживание", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Что, если верить названию скульптуры Ивана Шадра, является оружием пролетариата?", RightAnswer = "Булыжник", WrongAnswer1 = "Рогатина", WrongAnswer2 = "Кулак", WrongAnswer3 = "Молот", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Пирог с какой начинкой дал название веселому самодеятельному представлению?", RightAnswer = "Капуста", WrongAnswer1 = "Грибы", WrongAnswer2 = "Яблоки", WrongAnswer3 = "Клюква", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Что солдаты российской армии вклеивают в дембельские альбомы?", RightAnswer = "Фотографии", WrongAnswer1 = "Штабные карты", WrongAnswer2 = "Чертежи оружия", WrongAnswer3 = "Медкарты", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Кому Одиссей объяснял свое многолетнее отсутствие?", RightAnswer = "Жене", WrongAnswer1 = "Соседу", WrongAnswer2 = "Шефу", WrongAnswer3 = "Императору", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Как заканчивается строчка популярной песни: \"Я другой такой страны...\"?", RightAnswer = "Не знаю", WrongAnswer1 = "Не видел", WrongAnswer2 = "Не помню", WrongAnswer3 = "Не открывал", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Сколько букв в современном русском алфавите стоит между буквами М и Ж?", RightAnswer = "5", WrongAnswer1 = "3", WrongAnswer2 = "4", WrongAnswer3 = "6", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Как называют края шляпы?", RightAnswer = "Поля", WrongAnswer1 = "Нивы", WrongAnswer2 = "Огороды", WrongAnswer3 = "Наделы", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Какая процедура предусмотрена в некоторых ночных клубах?", RightAnswer = "Фейс-контроль", WrongAnswer1 = "Анфас-досмотр", WrongAnswer2 = "Облик-проверка", WrongAnswer3 = "Профиль-таможня", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Как заканчивается поговорка о бессмысленном деле: \"Решетом...\"?", RightAnswer = "воду носить", WrongAnswer1 = "муку молоть", WrongAnswer2 = "огород поливать", WrongAnswer3 = "чудеса творить", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Как заканчивается фраза из песни: \"Просто встретились...\"?", RightAnswer = "два одиночества", WrongAnswer1 = "три товарища", WrongAnswer2 = "родные братья", WrongAnswer3 = "гора с Магометом", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Театр с каким названием существует?", RightAnswer = "\"Ла Скала\"", WrongAnswer1 = "\"По Целовала\"", WrongAnswer2 = "\"От Няла\"", WrongAnswer3 = "\"Чмок Нула\"", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Что растёт в огороде?", RightAnswer = "Лук", WrongAnswer1 = "Пистолет", WrongAnswer2 = "Пулемёт", WrongAnswer3 = "Ракета СС-20", Difficulty = 1});
            _QuestionList.Add(new Question { QuestionName = "Как порой называют деспотичную женщину?", RightAnswer = "Жандарм в юбке", WrongAnswer1 = "Майор в декольте", WrongAnswer2 = "Ефрейтор в платье", WrongAnswer3 = "Сержант в бигуди", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Как заканчивается русская пословица: \"Была бы изба...\"?", RightAnswer = "будут и тараканы", WrongAnswer1 = "сделаем евроремонт", WrongAnswer2 = "завершим приватизацию", WrongAnswer3 = "найдем злую собаку", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Что нужно для детской игры в классики?", RightAnswer = "Клетки на асфальте", WrongAnswer1 = "Боксерский ринг", WrongAnswer2 = "Партитура", WrongAnswer3 = "Ракетка", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Что группа ЛЮБЭ требовала от Америки, призывая ее не валять дурака?", RightAnswer = "Отдать Аляску", WrongAnswer1 = "Забыть о гамбургерах", WrongAnswer2 = "Освободить индейцев", WrongAnswer3 = "Закрыть Голливуд", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Какая фраза чаще всего звучит на аукционе?", RightAnswer = "Кто больше?", WrongAnswer1 = "Кто сильнее?", WrongAnswer2 = "Кто хитрее?", WrongAnswer3 = "Продано", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Сколько суток составляют високосный год?", RightAnswer = "366", WrongAnswer1 = "365", WrongAnswer2 = "364", WrongAnswer3 = "356", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Что Вячеслав Добрынин умолял не сыпать ему на рану в одной из песен", RightAnswer = "Соль", WrongAnswer1 = "Перец", WrongAnswer2 = "Сахар", WrongAnswer3 = "Стрептоцид", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Что царь Гордий завязал так, что Александру Македонскому пришлось взяться за меч?", RightAnswer = "Узел", WrongAnswer1 = "Шнурки", WrongAnswer2 = "Бант", WrongAnswer3 = "Беседа", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "В каком из этих фильмов главное действующее лицо В.И.Ленин", RightAnswer = "Человек с ружьем", WrongAnswer1 = "Человек-невидимка", WrongAnswer2 = "Человек-амфибия", WrongAnswer3 = "По кличке зверь", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "О чём писал Грибоедов, отмечая, что он «нам сладок и приятен» ?", RightAnswer = "Дым Отечества", WrongAnswer1 = "Дух купечества", WrongAnswer2 = "Дар пророчества", WrongAnswer3 = "Пыл девичества", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Какого персонажа нет в известной считалке «На золотом крыльце сидели» ?", RightAnswer = "Кузнеца", WrongAnswer1 = "Сапожника", WrongAnswer2 = "Короля", WrongAnswer3 = "Портного", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Какой специалист занимается изучением неопознанных летающих объектов?", RightAnswer = "Уфолог", WrongAnswer1 = "Кинолог", WrongAnswer2 = "Сексопатолог", WrongAnswer3 = "Психиатр", Difficulty = 1 });
            _QuestionList.Add(new Question { QuestionName = "Как называется изделие из простейших петель, связанные крючком?", RightAnswer = "Косичка", WrongAnswer1 = "Хвостик", WrongAnswer2 = "Бантик", WrongAnswer3 = "Ленточка", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Что, согласно легенде, сказал, чешский мыслитель Ян Гус о старушке, подбросившей хвороста в огонь?", RightAnswer = "О, святая простота!", WrongAnswer1 = "Да будет свет!", WrongAnswer2 = "Остановись, мгновенье, ты прекрасно!", WrongAnswer3 = "Ну, бабка, жжёшь!", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "У какой из лошадей золотистая окраска и светлые грива и хвост?", RightAnswer = "У соловой", WrongAnswer1 = "У гнедой", WrongAnswer2 = "У чалой", WrongAnswer3 = "У вороной", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "На стихи какого поэта Александр Барыкин написал песню \"Букет\"?", RightAnswer = "Николай Рубцов", WrongAnswer1 = "Евгений Евтушенко", WrongAnswer2 = "Иосиф Уткин", WrongAnswer3 = "Римма Казакова", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Какой из этих фильмов посвящен спорту?", RightAnswer = "Ход белой королевы", WrongAnswer1 = "Шах и мат", WrongAnswer2 = "Рокировка в длинную сторону", WrongAnswer3 = "Сицилианская защита", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "У какого летательного аппарата вместо шасси ноги летчика?", RightAnswer = "Дельтаплан", WrongAnswer1 = "Автожир", WrongAnswer2 = "Планер", WrongAnswer3 = "Авиетка", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Какой из этих фильмов не повествует о приключениях Эраста Фандорина?", RightAnswer = "Гибель империи", WrongAnswer1 = "Азазель", WrongAnswer2 = "Турецкий гамбит", WrongAnswer3 = "Статский советник", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Какой праздник православные отмечают накануне Великого Поста?", RightAnswer = "Масленица", WrongAnswer1 = "Троица", WrongAnswer2 = "Яблочный Спас", WrongAnswer3 = "Рождество Христово", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Какой музыкант придумал себе образ космического пришельца Зигги?", RightAnswer = "Девид Боуи", WrongAnswer1 = "Элтон Джон", WrongAnswer2 = "Майкл Джексон", WrongAnswer3 = "Брайан Адамс", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Какое из этих названий переводится на русский язык, как \"много островов\"?", RightAnswer = "Полинезия", WrongAnswer1 = "Филиппины", WrongAnswer2 = "Япония", WrongAnswer3 = "Самоа", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Огромным размером чего отличается лисичка фенек?", RightAnswer = "Ушей", WrongAnswer1 = "Хвоста", WrongAnswer2 = "Глаз", WrongAnswer3 = "Носом", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Где находится город Касли, известный во всем мире изделиями из литого металла?", RightAnswer = "Россия", WrongAnswer1 = "Великобритания", WrongAnswer2 = "США", WrongAnswer3 = "Канада", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Что поручено охранять сотне стражников швейцарской гвардии?", RightAnswer = "Папу и Ватикан", WrongAnswer1 = "Штаб-квартиру ООН", WrongAnswer2 = "Букингемский дворец", WrongAnswer3 = "Белый дом в Вашингтоне", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Какая горная система самая протяженная на Земле?", RightAnswer = "Анды", WrongAnswer1 = "Гималаи", WrongAnswer2 = "Аппалачи", WrongAnswer3 = "Альпы", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Какого названия нет среди трех составляющих элементов тройного прыжка?", RightAnswer = "Полет", WrongAnswer1 = "Скачок", WrongAnswer2 = "Шаг", WrongAnswer3 = "Прыжок", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "По какой железной дороге путешествуют из Санкт-Петербурга в Москву?", RightAnswer = "Октябрьская", WrongAnswer1 = "Горьковская", WrongAnswer2 = "Московская", WrongAnswer3 = "Северная", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Кому Байрон посвятил строки: \"О нем острили в штабе иногда, а он в ответ брал с ходу города\"?", RightAnswer = "А.В.Суворову", WrongAnswer1 = "М.И.Кутузову", WrongAnswer2 = "Г.А.Потемкину", WrongAnswer3 = "П.И.Багратиону", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "На каком континенте все государства республики?", RightAnswer = "Южная Америка", WrongAnswer1 = "Северная Америка", WrongAnswer2 = "Евразия", WrongAnswer3 = "Африка", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Какой футболист за всю спортивную карьеру не изменил своему клубу?", RightAnswer = "Лев Яшин", WrongAnswer1 = "Александр Мостовой", WrongAnswer2 = "Ринат Дасаев", WrongAnswer3 = "Олег Протасов", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "На какой станции была оборудована первая космическая баня?", RightAnswer = "Мир", WrongAnswer1 = "МКС", WrongAnswer2 = "Алмаз", WrongAnswer3 = "Салют", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Как называется разновидность воды, в которой атом водорода замещён его изотопом дейтерием?", RightAnswer = "Тяжёлая", WrongAnswer1 = "Лёгкая", WrongAnswer2 = "Средняя", WrongAnswer3 = "Невесомая", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Какой из этих алкогольных напитков не употребляют в горячем виде?", RightAnswer = "Крюшон", WrongAnswer1 = "Грог", WrongAnswer2 = "Пунш", WrongAnswer3 = "Глинтвейн", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Из какого материала изготавливается керамическая посуда?", RightAnswer = "Глина", WrongAnswer1 = "Стекло", WrongAnswer2 = "Гипс", WrongAnswer3 = "Керамика", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Устройством какого из этих инструментов не предусмотрены меха для нагнетания воздуха?", RightAnswer = "Волторна", WrongAnswer1 = "Орган", WrongAnswer2 = "Волынка", WrongAnswer3 = "Шарманка", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Как называется южноамериканский аналог степи?", RightAnswer = "Пампасы", WrongAnswer1 = "Прерии", WrongAnswer2 = "Тундра", WrongAnswer3 = "Саванна", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Какой дворец является резиденцией президента РФ в Санкт-Петербурге?", RightAnswer = "Константиновский", WrongAnswer1 = "Зимний", WrongAnswer2 = "Михайловский", WrongAnswer3 = "Таврический", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Что такое десница?", RightAnswer = "Рука", WrongAnswer1 = "Бровь", WrongAnswer2 = "Глаз", WrongAnswer3 = "Шея", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "В какое море впадает река Урал?", RightAnswer = "Каспийское", WrongAnswer1 = "Азовское", WrongAnswer2 = "Чёрное", WrongAnswer3 = "Средиземное", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "На что кладут руку члены английского общества лысых во время присяги?", RightAnswer = "Бильярдный шар", WrongAnswer1 = "Баскетбольный мяч", WrongAnswer2 = "Апельсин", WrongAnswer3 = "Кокосовый орех", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Как назывался каменный монолит, на котором установлен памятник Петру I в Санкт-Петербурге?", RightAnswer = "Гром-камень", WrongAnswer1 = "Дом-камень", WrongAnswer2 = "Гора-камень", WrongAnswer3 = "Разрыв-камень", Difficulty = 2 });
            _QuestionList.Add(new Question { QuestionName = "Как Пётр Ильич Чайковский назвал свою серенаду для скрипки с оркестром си-бемоль минор?", RightAnswer = "Меланхолическая", WrongAnswer1 = "Флегматическая", WrongAnswer2 = "Холерическая", WrongAnswer3 = "Сангвиническая", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Какое сравнение не использовал Пушкин, противопоставляя Онегина и Ленского?", RightAnswer = "Земля и небо", WrongAnswer1 = "Волна и камень", WrongAnswer2 = "Стихи и проза", WrongAnswer3 = "Лед и пламень", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "От какой империи Россия унаследовала двуглавого орла на гербе?", RightAnswer = "Византийская", WrongAnswer1 = "Римская", WrongAnswer2 = "Османская", WrongAnswer3 = "Китайская", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Команда какой страны стала победительницей первого чемпионата мира по футболу?", RightAnswer = "Уругвай", WrongAnswer1 = "Ямайка", WrongAnswer2 = "Бразилия", WrongAnswer3 = "Аргентина", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Кого из этих писателей англичане считают прародителем разведслужбы Великобритании?", RightAnswer = "Даниель Дефо", WrongAnswer1 = "Джонатан Свифт", WrongAnswer2 = "Генри Филдинг", WrongAnswer3 = "Чарльз Диккенс", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Какое животное имеет второе название — кугуар?", RightAnswer = "Пума", WrongAnswer1 = "Оцелот", WrongAnswer2 = "Леопард", WrongAnswer3 = "Пантера", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Что в России 19 века делали в дортуаре?", RightAnswer = "Спали", WrongAnswer1 = "Ели", WrongAnswer2 = "Ездили верхом", WrongAnswer3 = "Купались", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Что коллекционировал германский канцлер Отто фон Бисмарк?", RightAnswer = "Градусники", WrongAnswer1 = "Курительные трубки", WrongAnswer2 = "Пивные кружки", WrongAnswer3 = "Велосипеды", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Под какой фамилией нам известен драматург М.Маршак - автор пьессы \"Так победим\"?", RightAnswer = "Шатров", WrongAnswer1 = "Арбузов", WrongAnswer2 = "Родзинский", WrongAnswer3 = "Зорин", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Сколько судейских бригад оценивают выступление в художественной гимнастике на олимпийских играх?", RightAnswer = "3", WrongAnswer1 = "2", WrongAnswer2 = "1", WrongAnswer3 = "4", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Как раньше называлась буква кириллицы, которую сегодня мы называем \"Т\"?", RightAnswer = "Твердо", WrongAnswer1 = "Так", WrongAnswer2 = "Топор", WrongAnswer3 = "Трон", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Что в 1903 году помогло выбраться из ледового плена кораблю \"Гаусс\" немецкой южнополярной экспедиции?", RightAnswer = "Зола", WrongAnswer1 = "Динамит", WrongAnswer2 = "Кипяток", WrongAnswer3 = "Машинное масло", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Где устанавливают спинакер?", RightAnswer = "На парусной яхте", WrongAnswer1 = "На метеорологической станции", WrongAnswer2 = "В ветеринарной клинике", WrongAnswer3 = "В угольной шахте", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Где родилась топ-модель Наоми Кемпбелл?", RightAnswer = "Великобритания", WrongAnswer1 = "США", WrongAnswer2 = "Сомали", WrongAnswer3 = "Боцвана", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Какой композитор поглаживал нос пальцами, полагая, что это избавляет от курносости?", RightAnswer = "А.Н.Скрявин", WrongAnswer1 = "С.И.Танеев", WrongAnswer2 = "Н.А.Римский-Корсаков", WrongAnswer3 = "С.В.Рахманинов", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Какую из семи сталинских высоток Москвы построили последней?", RightAnswer = "Гостиница \"Украина\"", WrongAnswer1 = "Здание МИДа", WrongAnswer2 = "Здание МГУ", WrongAnswer3 = "Дом на Площади Восстания", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Какой химический элемент назван в честь злого подземного гнома?", RightAnswer = "Кобальт", WrongAnswer1 = "Гафний", WrongAnswer2 = "Бериллий", WrongAnswer3 = "Теллур", Difficulty = 3 });
            _QuestionList.Add(new Question { QuestionName = "Кто из этих философоф в 1864 году написал музыку на стихи А.С.Пушкина \"Заклинание\" и \"Зимний вечер\"", RightAnswer = "Ницше", WrongAnswer1 = "Гегель", WrongAnswer2 = "Шопенгауэр", WrongAnswer3 = "Юнг", Difficulty = 4 });
            _QuestionList.Add(new Question { QuestionName = "В каком городе в 1932 году был проведён первый международный кинофестиваль?", RightAnswer = "Венеция", WrongAnswer1 = "Канны", WrongAnswer2 = "Париж", WrongAnswer3 = "Берлин", Difficulty = 4 });
            _QuestionList.Add(new Question { QuestionName = "Сколько раз в сутки подзаводят куранты на Спасской башне Кремля?", RightAnswer = "2", WrongAnswer1 = "1", WrongAnswer2 = "3", WrongAnswer3 = "4", Difficulty = 4 });
            _QuestionList.Add(new Question { QuestionName = "Кто первым получил Нобелевскую премию по литературе?", RightAnswer = "Поэт", WrongAnswer1 = "Романист", WrongAnswer2 = "Драматург", WrongAnswer3 = "Эссеист", Difficulty = 4 });
            _QuestionList.Add(new Question { QuestionName = "Как назвали первую кимберлитовую трубку, открытую Ларисой Попугаевой 21 августа 1954 года?", RightAnswer = "Зарница", WrongAnswer1 = "Удачная", WrongAnswer2 = "Мир", WrongAnswer3 = "Советская", Difficulty = 4 });
            _QuestionList.Add(new Question { QuestionName = "Кто из перечислинных был пажом во времена Екатерины II?", RightAnswer = "А.Н.Радищев", WrongAnswer1 = "Д.И.Фонвизин", WrongAnswer2 = "Г.Р.Державин", WrongAnswer3 = "Н.М.Карамзин", Difficulty = 4 });
            _QuestionList.Add(new Question { QuestionName = "В честь какого растения область Фриули-Венеция-Джулия в Италии ежегодно проводит трехмесячный фестиваль?", RightAnswer = "Спаржа", WrongAnswer1 = "Лук", WrongAnswer2 = "Фасоль", WrongAnswer3 = "Артишок", Difficulty = 4 });
            _QuestionList.Add(new Question { QuestionName = "Что Иван Ефремов в романе \"Лезвие бритвы\" назвал наивысшей степенью целесообразности?", RightAnswer = "Красоту", WrongAnswer1 = "Смерть", WrongAnswer2 = "Мудрость", WrongAnswer3 = "Свободу", Difficulty = 4 });
            _QuestionList.Add(new Question { QuestionName = "В какой из этих столиц бывших союзных республик раньше появилось метро?", RightAnswer = "Тбилиси", WrongAnswer1 = "Ереван", WrongAnswer2 = "Баку", WrongAnswer3 = "Минск", Difficulty = 4 });
            _QuestionList.Add(new Question { QuestionName = "Сколько морей омывают Балканский полуостров?", RightAnswer = "6", WrongAnswer1 = "3", WrongAnswer2 = "4", WrongAnswer3 = "5", Difficulty = 4 });
            _QuestionList.Add(new Question { QuestionName = "Сколько черепов взял в руки Гамлет, прежде чем взять череп Йорека?", RightAnswer = "2", WrongAnswer1 = "1", WrongAnswer2 = "4", WrongAnswer3 = "3", Difficulty = 4 });
            _QuestionList.Add(new Question { QuestionName = "Продолжите фразу Гая Юлия Цезаря: \"Пусть ненавидят, лишь бы...\"?", RightAnswer = "Боялись", WrongAnswer1 = "Уважали", WrongAnswer2 = "Подчинялись", WrongAnswer3 = "Не забывали", Difficulty = 4 });
        }
    }
}
